In [1]:
import torch
import torch.nn.functional as F

In [2]:
img = torch.rand(6, 6)
img = img.unsqueeze(dim = 0).unsqueeze(dim = 0)
kernel = torch.ones(3, 3)
kernel  = kernel.unsqueeze(dim = 0).unsqueeze(dim = 0)

In [3]:
layer = torch.nn.Conv2d(in_channels= 1, out_channels= 3, kernel_size= 3, stride= 1, padding= 0)
output = layer(img)

In [5]:
print(output.shape)
print(output)

torch.Size([1, 3, 4, 4])
tensor([[[[ 0.5213,  0.4216,  0.7662,  0.5754],
          [ 0.1986,  0.2131,  0.1242,  0.2211],
          [ 0.1049,  0.2385,  0.0222,  0.2087],
          [ 0.3975,  0.3670,  0.5266,  0.4649]],

         [[-0.0597, -0.1193,  0.1180, -0.1800],
          [-0.0986,  0.1540, -0.0432,  0.0194],
          [ 0.0455,  0.0550, -0.0252,  0.0028],
          [-0.0086, -0.0812,  0.0661, -0.0954]],

         [[ 0.4928,  0.6244,  0.3894,  0.4200],
          [ 0.7143,  0.4756,  0.4946,  0.4101],
          [ 0.6192,  0.6047,  0.7090,  0.5944],
          [ 0.4665,  0.6342,  0.4814,  0.7979]]]],
       grad_fn=<ConvolutionBackward0>)


In [9]:
kernel = torch.ones(size=(3, 1, 3, 3))
print(kernel)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [10]:
output = F.conv2d(img, kernel, stride= 1, padding= 0)
print(output, output.shape)

tensor([[[[4.1842, 4.4336, 4.7258, 4.0594],
          [5.0561, 5.5894, 6.2230, 5.7845],
          [4.7459, 5.7360, 6.5182, 6.4048],
          [4.1200, 5.1612, 4.8040, 5.2231]],

         [[4.1842, 4.4336, 4.7258, 4.0594],
          [5.0561, 5.5894, 6.2230, 5.7845],
          [4.7459, 5.7360, 6.5182, 6.4048],
          [4.1200, 5.1612, 4.8040, 5.2231]],

         [[4.1842, 4.4336, 4.7258, 4.0594],
          [5.0561, 5.5894, 6.2230, 5.7845],
          [4.7459, 5.7360, 6.5182, 6.4048],
          [4.1200, 5.1612, 4.8040, 5.2231]]]]) torch.Size([1, 3, 4, 4])
