In [8]:
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from sklearn.metrics import confusion_matrix
from torch import nn

In [9]:
transforms = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, ), (0.5, ))])
train = datasets.MNIST('.', train= True, download= True, transform= transforms)
test = datasets.MNIST('.', train= False, download= True, transform=transforms)
train_loader = DataLoader(train, batch_size=64, shuffle= True)
test_loader = DataLoader(test, batch_size= 64, shuffle= True)

In [10]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Conv2d(1, 32, kernel_size=3),
                                 nn.ReLU(),
                                 nn.MaxPool2d((2, 2), stride= 2),
                                 nn.Conv2d(32, 64, kernel_size=3), 
                                 nn.ReLU(),
                                 nn.MaxPool2d((2, 2), stride=2),
                                 nn.Conv2d(64, 32, kernel_size= 3),
                                 nn.ReLU(),
                                 nn.MaxPool2d((2, 2), stride= 2))
        self.classify_head = nn.Sequential(nn.Linear(32, 20, bias= True),
                                           nn.Linear(20, 10, bias= True))
    
    def forward(self, x):
        return self.classify_head(self.net(x).reshape(-1, 32))

In [11]:
model = CNN()
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

In [12]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
model.to(device=device)

cuda


CNN(
  (net): Sequential(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=(2, 2), stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
    (4): ReLU()
    (5): MaxPool2d(kernel_size=(2, 2), stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1))
    (7): ReLU()
    (8): MaxPool2d(kernel_size=(2, 2), stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classify_head): Sequential(
    (0): Linear(in_features=32, out_features=20, bias=True)
    (1): Linear(in_features=20, out_features=10, bias=True)
  )
)

In [14]:
for epoch in range(10):
    model.train()
    running_loss = 0.0
    for input, target in train_loader:
        input, target = input.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(input)
        loss = criterion(output, target)
        loss.backward()
        running_loss += loss.item()
        optimizer.step()
    print(f'Epoch - {epoch}, loss = {running_loss}')

Epoch - 0, loss = 2160.6764454841614
Epoch - 1, loss = 2149.515485048294
Epoch - 2, loss = 2136.6926374435425
Epoch - 3, loss = 2117.1690723896027
Epoch - 4, loss = 2081.1246058940887
Epoch - 5, loss = 2002.1716482639313
Epoch - 6, loss = 1804.4552952051163
Epoch - 7, loss = 1374.0778160095215
Epoch - 8, loss = 930.1589660644531
Epoch - 9, loss = 681.560250043869


In [16]:
torch.save(model, '../lab 6/ModelFiles/model.pt')

In [15]:
model.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for input, target in test_loader:
        output = model(input)
        val, index = torch.max(output, 1)
        all_preds.extend(index)
        all_labels.extend(target)
cm = confusion_matrix(all_labels, all_preds)
print(cm)
print(sum(p.numel() for p in model.parameters() if p.requires_grad))

[[ 904    0    4    0    4   16   49    1    1    1]
 [   0 1112    3    1    0    3    2    3   11    0]
 [   1    9  854   16    7    9   13   36   76   11]
 [   0    1   17  932    0   15    0   14   18   13]
 [   2    4    0    0  870    4   39    4    9   50]
 [   6    9    2   25    3  760   29    5   26   27]
 [  50    7    3    0   48   17  824    0    8    1]
 [   4    5   56   31   14    3    1  863   15   36]
 [   0   10   26   28    5   56   14   15  749   71]
 [   7    5    3   17   33   26    8   34   34  842]]
38150


In [18]:
from sklearn.metrics import accuracy_score
print(accuracy_score(all_labels, all_preds))

0.871
